name: CI - Tests & SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (backend)
        working-directory: API-BANCO
        run: npm ci

      - name: Run tests with coverage and junit report (backend)
        working-directory: API-BANCO
        env:
          JEST_JUNIT_OUTPUT: ./coverage/junit.xml
        run: npm run test:ci

      - name: SonarCloud Scan
        # Pin the action to a full commit SHA to avoid supply-chain surprises.
        # Replace the example SHA below with the latest commit SHA from the action's repository.
        # To find the SHA: visit https://github.com/SonarSource/sonarcloud-github-action/commits
        # pick the tag or commit you trust and copy the full 40-char SHA. Then replace the value.
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
